Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -66,16 +66,22 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: 22
           script: |
-            # Matar cualquier proceso que esté ejecutando el JAR
-            pkill -f 'java -jar /home/ubuntu/Proyecto-Portal-Empleado/Proyecto_Portal_Empleado-0.0.1-SNAPSHOT.jar' || true
-            sleep 5  # Esperar para asegurarse de que el proceso termine
+            # Encontrar el proceso del JAR y matarlo si existe
+            PID=$(pgrep -f 'java -jar /home/ubuntu/Proyecto-Portal-Empleado/Proyecto_Portal_Empleado-0.0.1-SNAPSHOT.jar')
+            if [ -n "$PID" ]; then
+              echo "Matando el proceso con PID $PID"
+              kill -TERM $PID
+              sleep 5  # Esperar para asegurarse de que el proceso termine
 
-            # Verificar si el proceso sigue corriendo
-            if pgrep -f 'java -jar /home/ubuntu/Proyecto-Portal-Empleado/Proyecto_Portal_Empleado-0.0.1-SNAPSHOT.jar'; then
-              echo "Error: el proceso sigue corriendo"
-              exit 1
+              # Verificar si el proceso sigue corriendo
+              if pgrep -f 'java -jar /home/ubuntu/Proyecto-Portal-Empleado/Proyecto_Portal_Empleado-0.0.1-SNAPSHOT.jar'; then
+                echo "Error: el proceso sigue corriendo"
+                exit 1
+              else
+                echo "Proceso detenido correctamente"
+              fi
             else
-              echo "Proceso detenido correctamente"
+              echo "No se encontró ningún proceso ejecutando el JAR"
             fi
 
             # Navegar al directorio y limpiar archivos antiguos de logs
