Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,6 +58,48 @@ jobs:
         working-directory: ./Proyecto_Portal_Empleado_Servidor
         run: ./mvnw clean package
 
+      - name: Run JAR on EC2
+        uses: appleboy/ssh-action@v0.1.4
+        with:
+          host: 52.86.210.155
+          username: ubuntu
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            # Verificar si el puerto 8080 ya está en uso
+            if sudo ss -tulnp | grep 8080; then
+              echo "El puerto 8080 ya está ocupado. No se puede iniciar el nuevo JAR."
+              exit 1
+            else
+              echo "El puerto 8080 está libre. Iniciando el nuevo JAR."
+              # Navegar al directorio y limpiar archivos antiguos de logs
+              cd /home/ubuntu/Proyecto-Portal-Empleado
+              rm -f nohup.out output.log
+
+              # Ejecutar el nuevo JAR en segundo plano
+              nohup java -jar Proyecto_Portal_Empleado-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
+              sleep 5  # Esperar unos segundos para asegurarse de que el proceso arranca
+
+              # Verificar si el JAR está corriendo
+              if pgrep -f 'java -jar /home/ubuntu/Proyecto-Portal-Empleado/Proyecto_Portal_Empleado-0.0.1-SNAPSHOT.jar'; then
+                echo "JAR ejecutado correctamente."
+                echo "Los logs están siendo registrados en /home/ubuntu/Proyecto-Portal-Empleado/output.log"
+              else
+                echo "Error al ejecutar el JAR."
+                exit 1
+              fi
+            fi
+
+      - name: Check JAR logs
+        uses: appleboy/ssh-action@v0.1.4
+        with:
+          host: 52.86.210.155
+          username: ubuntu
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            cat /home/ubuntu/Proyecto-Portal-Empleado/output.log
+
       - name: Pull latest code on EC2
         uses: appleboy/ssh-action@v0.1.4
         with:
@@ -80,8 +122,8 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: 22
           script: |
-            cd /home/ubuntu/Proyecto-Portal-Empleado
-            docker build -t nombre-imagen .
-            docker stop nombre-contenedor || true
-            docker rm nombre-contenedor || true
-            docker run -d -p 8080:8080 --name nombre-contenedor nombre-imagen
+            cd /home/ubuntu/Proyecto-Portal-Empleado/Proyecto_Portal_Empleado_Servidor
+            docker build -t proyecto-portal-empleado .
+            docker stop proyecto-portal-empleado-container || true
+            docker rm proyecto-portal-empleado-container || true
+            docker run -d -p 8080:8080 --name proyecto-portal-empleado-container proyecto-portal-empleado
