Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -66,28 +66,29 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: 22
           script: |
-            # Encontrar el proceso del JAR y matarlo si existe
+           # Encontrar el proceso del JAR y matarlo si existe
             PID=$(pgrep -f 'java -jar /home/ubuntu/Proyecto-Portal-Empleado/Proyecto_Portal_Empleado-0.0.1-SNAPSHOT.jar')
             if [ -n "$PID" ]; then
               echo "Matando el proceso con PID $PID"
               kill -TERM $PID
+              KILL_EXIT_CODE=$?  # Capturamos el código de salida de kill
               sleep 5  # Esperar para asegurarse de que el proceso termine
-
-              # Verificar si el proceso sigue corriendo
-              if pgrep -f 'java -jar /home/ubuntu/Proyecto-Portal-Empleado/Proyecto_Portal_Empleado-0.0.1-SNAPSHOT.jar'; then
-                echo "Error: el proceso sigue corriendo"
-                exit 1
-              else
+            
+              # Si el proceso fue matado exitosamente con el código 143, continuar
+              if [ $KILL_EXIT_CODE -eq 143 ] || [ $KILL_EXIT_CODE -eq 0 ]; then
                 echo "Proceso detenido correctamente"
+              else
+                echo "Error al intentar detener el proceso con PID $PID"
+                exit 1
               fi
             else
               echo "No se encontró ningún proceso ejecutando el JAR"
             fi
-
+            
             # Navegar al directorio y limpiar archivos antiguos de logs
             cd /home/ubuntu/Proyecto-Portal-Empleado
             rm -f nohup.out output.log
-
+            
             # Verificar que no haya otro proceso en el puerto 8080 con un timeout de espera
             TIMEOUT=60
             while sudo ss -tulnp | grep 8080; do
@@ -99,11 +100,11 @@ jobs:
                 exit 1
               fi
             done
-
+            
             # Ejecutar el nuevo JAR en segundo plano
             nohup java -jar Proyecto_Portal_Empleado-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
             sleep 5  # Esperar unos segundos para asegurarse de que el proceso arranca
-
+            
             # Verificar si el JAR está corriendo
             if pgrep -f 'java -jar /home/ubuntu/Proyecto-Portal-Empleado/Proyecto_Portal_Empleado-0.0.1-SNAPSHOT.jar'; then
               echo "JAR ejecutado correctamente."
@@ -112,6 +113,7 @@ jobs:
               echo "Error al ejecutar el JAR."
               exit 1
             fi
+
 
       # Step opcional: Verificar los logs
       - name: Check JAR logs
